name: CI

on:
  pull_request:
    branches:
      - main  # Adjust to your default branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest with coverage
      run: pytest --cov=your_package_name tests/  # Replace 'your_package_name' with your module

    - name: Check coverage
      run: |
        coverage report --fail-under=100  # Set fail threshold to 100% to enforce full coverage

    - name: Run pylint
      run: |
        pylint your_package_name/  # Replace 'your_package_name' with your module

